<!--
  - Copyright (c) 2023. Selldone® Business OS™
  -
  - Author: M.Pajuhaan
  - Web: https://selldone.com
  - ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
  -
  - All rights reserved. In the weave of time, where traditions and innovations intermingle, this content was crafted.
  - From the essence of thought, through the corridors of creativity, each word, and sentiment has been molded.
  - Not just to exist, but to inspire. Like an artist's stroke or a sculptor's chisel, every nuance is deliberate.
  - Our journey is not just about reaching a destination, but about creating a masterpiece.
  - Tread carefully, for you're treading on dreams.
  -->

<template>
  <v-card
    class="s--shop-card s--shadow-no-padding pb-4 mb-16"
    :color="ThemeColorDeepDark"
  >
    <!-- ▆▆▆▆▆▆▆▆▆▆▆▆▆▆▆▆▆ Order > Toolbar ▆▆▆▆▆▆▆▆▆▆▆▆▆▆▆▆▆ -->

    <v-toolbar
      :color="ThemeColorDeepDark"
      dark
      extended
      extension-height="64px"
      flat
      style="overflow-x: auto"
    >
      <template v-slot:extension>
        <div style="height: 64px"></div>
      </template>

      <!-- ⦿ Back -->

      <u-button-circle
        :icon="$t('icons.arrow_back')"
        :to="
          buildReturnRoute(
            $route.query.return_id
              ? window.$storefront.routes.USER_RETURN_REQUESTS
              : window.$storefront.routes.HISTORY_ORDERS_POS,
          )
        "
        :tooltip="$t('global.actions.back')"
      />

      <v-spacer></v-spacer>

      <u-loading-ellipsis v-if="busy" css-mode></u-loading-ellipsis>

      <v-spacer></v-spacer>

      <div class="d-flex flex-column align-center px-3">
        {{ $t("global.commons.order_detail") }}
        <div v-if="USER()" class="small mt-1">
          {{ USER().name }}
        </div>
      </div>
      <img
        :src="require('@selldone/core-js/assets/order-types/basket-pos.svg')"
        class="me-5"
        height="28"
        width="28"
      />
    </v-toolbar>

    <!-- ▆▆▆▆▆▆▆▆▆▆▆▆▆▆▆▆▆ Order > Card ▆▆▆▆▆▆▆▆▆▆▆▆▆▆▆▆▆ -->

    <v-card class="s--card-window-content" flat style="min-height: 80vh">
      <router-view
        v-if="basket"
        :basket="basket"
        @request:refresh="fetchOrderInfo()"
      />
    </v-card>
  </v-card>
</template>

<script lang="ts">
import NotificationService from "@selldone/components-vue/plugins/notification/NotificationService.ts";

import { GtagEcommerce } from "@selldone/components-vue/plugins/gtag/GtagEcommerce";
import { RouteMixin } from "@selldone/components-vue/mixin/route/RouteMixin.ts";
import { Basket } from "@selldone/core-js";
import ULoadingEllipsis from "@selldone/components-vue/ui/loading/ellipsis/ULoadingEllipsis.vue";
import TemplateMixin from "@selldone/components-vue/mixin/template/TemplateMixin.ts";
import {EventBus} from "@selldone/core-js/events/EventBus.ts";

export default {
  name: "SStorefrontPOSOrderDetailMasterLayout",
  mixins: [RouteMixin, TemplateMixin],

  components: { ULoadingEllipsis },
  inject: ["$shop"],
  props: {},

  data: function () {
    return {
      basket: null,

      busy: false,
    };
  },

  computed: {},

  watch: {},
  created() {
    this.setPageTitle(`Order POS-` + this.$route.params.basket_id);
    this.fetchOrderInfo();
  },
  mounted() {
    EventBus.$on("on-payment-completed", ({ order_type, order_id }) => {
      console.log("on-payment-completed", order_type, order_id);
      if (this.basket && this.basket.id === order_id) this.fetchOrderInfo();
    });
  },
  beforeUnmount() {
    EventBus.$off("on-payment-completed");
  },

  methods: {
    fetchOrderInfo() {
      const shop_name = this.$shop.name;
      const basket_id = this.$route.params.basket_id;

      this.busy = true;
      axios
        .get(window.XAPI.GET_ORDER_POS_BASKET_INFO(shop_name, basket_id), {
          params: {
            /**
               This property holds the signature from the URL query parameters.
               The signature is a cryptographic hash that ensures the integrity and authenticity
               of the URL, preventing tampering. It's typically generated by shop staff when creating
               secure, time-limited URLs to display order details.
               */

            signature: this.$route.query.signature,
            /**
               This property holds the timestamp from the URL query parameters.
               The timestamp indicates when the URL was created and is used to ensure the URL's validity
               within a specific time frame. Like the signature, this is also generated by shop staff
               when creating secure URLs to display order details.
               */
            timestamp: this.$route.query.timestamp,
          },
        })
        .then(({ data }) => {
          if (!data.error) {
            this.basket = data.basket;

            if (this.basket.status === Basket.Status.Payed.code)
              GtagEcommerce.MeasuringPurchasesBasket(this.basket);
          } else {
            NotificationService.showErrorAlert(null, data.error_msg);
          }
        })
        .catch((error) => {
          NotificationService.showLaravelError(error);
        })
        .finally(() => {
          this.busy = false;
        });
    },
  },
};
</script>

<style lang="scss" scoped></style>
